src/v1.json

- snake_caseをcamelCaseに修正
- snake_caseの修正漏れを解消

snake_caseの修正漏れを解消

---

package.json

fix go dirname

---

.github/workflows/generate_backend.yaml
gin/models.config.yaml
gin/server.config.yaml
package.json

Gin file separate

---

.github/workflows/generate_backend.yaml

fix workflow condition

---

.github/workflows/generate_backend.yaml
package.json

fix workflow

---

.github/workflows/generate_backend.yaml

fix workflow templates

---

.github/workflows/generate_backend.yaml
.github/workflows/generate_frontend.yaml

Add workflow trigger path

---

.github/workflows/generate_backend.yaml

Add step for gin server

---

.github/workflows/generate_backend.yaml
gin/server.config.yaml

fix gin package name

---

src/v1.json

fix server url

---

.github/workflows/generate_lib.yaml
gin/models.config.yaml

Add generate for lib

---

src/v1.json

組み込み型を利用する

---

.github/workflows/generate_lib.yaml
gin/models.config.yaml

change models dir for lib

---

src/v1.json

use enum for status

---

.github/workflows/generate_backend.yaml
gin/models.config.yaml
gin/repackage.awk
package.json

backendのmodelsとserverのパッケージを分割するためのスクリプト
マージ後CIの結果を確認する

Add split package script for backend

---

.github/workflows/generate_backend.yaml

CIから非推奨の構文を削除

---

.github/workflows/generate_backend.yaml
gin/repackage.awk

fix importing package path

---

gin/models.config.yaml

fix generating package name

---

.github/release.yml

リリースノートの構成を設定するファイルを作成
この PR マージ後、リリース時に意図した構成でリリースノートが作成されるか確認する

CVS-157 リリースノートの設定ファイルの作成

---

src/v1.json

VMの電源状態に取る値を変更した
ローカルでmockサーバを立ち上げてAPIのレスポンス・リクエストを確認

CVS-159 VMの電源状態の変更

---

src/v1.json

スキーマ定義のリファクタリング
prism モックサーバを立てて curl で動作確認

CVS-160 スキーマ定義のリファクタリング

---

src/v1.json

request body を移動させた
コードジェネレータに request body から型を生成する機能がなかったため
モックサーバを立てて curl コマンドで検証
``` 
$ curl -X POST http://localhost:4010/api/v1/vms -H 'content-type: application/json' -d '{"name": "test", "cpu": 2, "memory": 4096}' | jq
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100   256  100   214  100    42  23400   4592 --:--:-- --:--:-- --:--:-- 32000
{
"vm": {
"name": "ubuntu",
"metadata": {
"id": "4e0a3c48-f483-422a-b520-2820207cef42",
"api_version": "v1"
},
"memory": 2048,
"cpu": 4,
"devices": {
"disk": [
{
"name": "ubuntu22.04",
"pool": "default",
"type": "qcow2",
"device": "disk"
}
]
}
}
}
```
```
$ curl -X PATCH http://127.0.0.1:4010/api/v1/vms/02e962cf-2402-b400-9430-1db532b382d6 -H 'content-type: …
```

CVS-167 request body を Paths の schema に直接記述

---

package.json
yarn.lock

ひとまずforkを使うことにする。
frontendに飛んでくるはずのPRを確認する

CVS-176 openapi2aspidaをforkに切り替え

---

.github/workflows/generate_backend.yaml
.github/workflows/generate_frontend.yaml
package.json
yarn.lock

CVS-180 openapi2aspidaを上流に戻す

---

src/v1.json

CVS-207 VM電源操作のスキーマ見直し

---

src/v1.json

CVS-207 スキーマ内のenumをmodelsに切り出し

---

.github/workflows/generate_backend.yaml
.github/workflows/generate_frontend.yaml

CVS-207 CIでベースブランチを参照させる

---

.github/release.yml

CVS-214 リリースノートに載せる authors から renovate を除外

---

.github/workflows/build_redoc.yaml
.github/workflows/generate_backend.yaml
.github/workflows/generate_frontend.yaml
.github/workflows/test.yaml

https://github.com/actions/cache/blob/main/examples.md#node---npm

CVS-209 github actionsの記法を変更

---

src/v1.json

CVS-219 VM削除のエンドポイントを作成

---

src/v1.json

CVS-219 intをuint64に戻す

---

src/v1.json

CVS-219 エンドポイントにタグを追加

---

.github/workflows/generate_frontend.yaml

CVS-209 frontend内でyarnのキャッシュを使用する

---

renovate.json

CVS-231 renovateを調整

---

renovate.json

CVS-261 Renovate の構文修正

---

LICENSE
README.md

CVS-263 README を作成
